### ISSUE TITLE
How is it related to oracledb ?

### ISSUE THREAD

**Issue by Cheyenne55** [carpassgeek/express-oracleconnection#1]
Dear carpass,

Can you explain how your module is related to official oracledb module ?

Regards

**Comment by carpassgeek** [comment]
@Cheyenne55 - It simply allows the connection (or connection pool) to be used in Express middleware so you can simply "request.getOracleConnection" anywhere in the routers and avoid code duplication.  express-myconnection has more details and this is effectively exactly the same as that project but with Oracle rather than MySQL : https://github.com/pwalczyszyn/express-myconnection

Sorry for the delay, I haven't been keeping up with my email very well for the last few months.
